In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import datasets
from sklearn.datasets import load_digits

In [3]:
digits = load_digits()

In [4]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [5]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
X = digits.data
y = digits.target

In [7]:
X.shape

(1797, 64)

In [8]:
y.shape

(1797,)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)

In [11]:
X_train.shape

(1437, 64)

In [12]:
y_train

array([9, 6, 2, ..., 5, 8, 0])

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [16]:
lda = LinearDiscriminantAnalysis()
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test) 

In [17]:
X_train.shape

(1437, 9)

In [18]:
X_train

array([[ 2.80566615, -3.58384737, -1.72905171, ...,  0.65768728,
         0.96754789, -1.40456913],
       [-2.75661928, -2.00895933,  2.57964884, ...,  0.53498907,
        -1.90634947,  1.82179468],
       [ 3.66043385,  1.02673895,  4.26626285, ...,  0.70757632,
         0.55907971, -1.10041881],
       ...,
       [-1.14118893, -0.28362312, -3.72900996, ..., -0.31856731,
        -0.89716402,  0.26622198],
       [ 1.03203752,  0.05011817,  1.14131861, ...,  1.52829437,
         2.49809883,  2.0555113 ],
       [-0.56178563, -4.14422424,  1.28361517, ...,  0.43008297,
        -0.25260197,  1.09392964]])

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rf1 = RandomForestClassifier()
rf1.fit(X_train, y_train)

RandomForestClassifier()

In [21]:
y_pred1 = rf1.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
acc = accuracy_score(y_test, y_pred1)

In [24]:
print(acc)

0.95


In [25]:
from xgboost import XGBClassifier

In [26]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(objective='multi:softprob')

In [27]:
y_pred = model.predict(X_test)

In [28]:
predictions = [round(value) for value in y_pred]

In [29]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.9388888888888889

In [30]:
for image, label in zip(digits.data[0:5], digits.target[0:5]):
    print(image)
    print(label)

[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
0
[ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
  3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
 16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
  0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]
1
[ 0.  0.  0.  4. 15. 12.  0.  0.  0.  0.  3. 16. 15. 14.  0.  0.  0.  0.
  8. 13.  8. 16.  0.  0.  0.  0.  1.  6. 15. 11.  0.  0.  0.  1.  8. 13.
 15.  1.  0.  0.  0.  9. 16. 16.  5.  0.  0.  0.  0.  3. 13. 16. 16. 11.
  5.  0.  0.  0.  0.  3. 11. 16.  9.  0.]
2
[ 0.  0.  7. 15. 13.  1.  0.  0.  0.  8. 13.  6. 15.  4.  0.  0.  0.  2.
  1. 13. 13.  0.  0.  0.  0.  0.  2. 15. 11.  1.  0.  0.  0.  0.  0.  1.
 12. 12.  1.  0.  0.  0.  0.  0.  1. 10.  8.  0.  0.  0.  8.  4. 

In [31]:
for i,j in enumerate(['a','b','c']):
    print(i)
    print(j)

0
a
1
b
2
c


In [32]:
def get_misclassified_index(y_pred,y_test):
    misclassification=[]#help us out to get the misclassified index value
    for index,(predicted,actual) in enumerate(zip(y_pred,y_test)):
        if predicted!=actual:
            misclassification.append(index)
            
    return misclassification

In [33]:
misclassification = get_misclassified_index(y_pred1,y_test)

In [34]:
len(misclassification)

18

In [35]:
misclassification

[17,
 25,
 27,
 37,
 46,
 80,
 95,
 132,
 146,
 215,
 224,
 229,
 273,
 278,
 313,
 336,
 344,
 359]